### ISSUE TITLE
Request more explanation about the output channel

### ISSUE THREAD

**Issue by lidaryani** [ugent-korea/pytorch-unet-segmentation#1]
Hi
I see your code and it is very useful ,but i have some questions about it.
in CleanU_Net you defined out_channels=2 , and as i am new in U-net network i don't know what is the meaning of this? Is that mean you have 2 labels( A=backgound and B=target ) and each channel refers to label A and B? channel 0 for label A and channel 1 for label B?
Could you please explain more about it?

**Comment by PyeongKim** [comment]
The out_channels = 2 means we have **two classes** as an output of the U-Net model.
In our case, we train the model to have channel 0 as background and channel 1 as foreground, which is the cell. Thus, it means **each channel represents each classes** (foreground and background).
For example, in the output of channel 0, 1 means this pixel is predicted as background and 0 means it is not predicted as background. 

Sorry for late reply.

**Comment by lidaryani** [comment]
Thank you for the clear explanation
