### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'src_device_obj'

### ISSUE THREAD

**Issue by naimji** [ugent-korea/pytorch-unet-segmentation#14]
generate test prediction
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\muh_k\Anaconda3\envs\latihans3\lib\site-packages\torch\serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-38e33bcff8a4> in <module>
      1 print("generate test prediction")
----> 2 test_model("../history/RMS/saved_models3/model_epoch_440.pwf", SEM_test_load, 440, "../history/RMS/result_test3")

~\belajar dl\implement biomedical image segmentation with the use of U-Net model\src\modules.py in test_model(model_path, data_test, epoch, save_folder_name)
     94                 image_t = Variable(images_t[:, index, :, :].unsqueeze(0).cuda())
     95                 # print(image_v.shape, mask_v.shape)
---> 96                 output_t = model(image_t)
     97                 output_t = torch.argmax(output_t, dim=1).float()
     98                 stacked_img = torch.cat((stacked_img, output_t))

~\Anaconda3\envs\latihans3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~\Anaconda3\envs\latihans3\lib\site-packages\torch\nn\parallel\data_parallel.py in forward(self, *inputs, **kwargs)
    148         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
    149         if len(self.device_ids) == 1:
--> 150             return self.module(*inputs[0], **kwargs[0])
    151         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    152         outputs = self.parallel_apply(replicas, inputs, kwargs)

~\Anaconda3\envs\latihans3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~\Anaconda3\envs\latihans3\lib\site-packages\torch\nn\parallel\data_parallel.py in forward(self, *inputs, **kwargs)
    141 
    142         for t in chain(self.module.parameters(), self.module.buffers()):
--> 143             if t.device != self.src_device_obj:
    144                 raise RuntimeError("module must have its parameters and buffers "
    145                                    "on device {} (device_ids[0]) but found one of "

~\Anaconda3\envs\latihans3\lib\site-packages\torch\nn\modules\module.py in __getattr__(self, name)
    574                 return modules[name]
    575         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 576             type(self).__name__, name))
    577 
    578     def __setattr__(self, name, value):

AttributeError: 'DataParallel' object has no attribute 'src_device_obj'

i get this eeror when i try to test the program? i need ur help how to resolve this issue? thanks

**Comment by yayaYsmile** [comment]
I'm having the same problem, did you fix it? Thank you very much!

**Comment by PyeongKim** [comment]
Attribute error is due to pytorch version (we used 0.4.x).
We have no plan to update our code to latest pytorch version.
Thanks

**Comment by yayaYsmile** [comment]
Thank you for your answer! I will lower the pytorch for experiments
