### ISSUE TITLE
training on own datase

### ISSUE THREAD

**Issue by anonymously123456** [ugent-korea/pytorch-unet-segmentation#17]
hi, In my dataset, there are four types of labels (0, 1, 2, 3).  Do I just need to change “ out_channels”  to 4, and after the change, there is an error，could you please tell me how to do the segmentation of four types of labels?
![image](https://user-images.githubusercontent.com/56376393/101017845-97f19500-35a5-11eb-95cb-39c3e6684e0d.png)

**Comment by PyeongKim** [comment]
In our code, we generalised training procedure for any dataset, but we made validation procedure just for our dataset. If you are willing to fix it, you can have a look to function that crops input images (as shown in your error message).
