### ISSUE TITLE
Test output order

### ISSUE THREAD

**Issue by dogabasaran** [ugent-korea/pytorch-unet-segmentation#2]
Hi, 
In your code, under the function test_model, you've noted: "# TODO: Change this to real image name so we know".
I want to test some files named 0.png, 1.png, 2.png, etc. However they are loaded into test_model in the order [0, 1, 10, 11, 12 ... 19, 2, 20, 21... ]. In what way can the generated test mask be named the same as the input file?
Thank you

Edit: Was able to resolve the issue. Thank you

**Comment by Alexander0211** [comment]
We just sloved this problem, hope can help you.
In dataset.py/class SEMDataTest(Dataset):

        img_list = os.listdir(image_path)
        img_list.sort(key=lambda x: int(x[:-4]))
        for i in range(len(img_list)):
            img_list[i] = image_path + img_list[i]
        #print(img_list)
        #self.image_arr = glob.glob(str(image_path) + str("/*"))
        self.image_arr = img_list
        self.in_size = in_size
        self.out_size = out_size
        self.data_len = len(self.image_arr)
