### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by Ng-ms** [ugent-korea/pytorch-unet-segmentation#3]
i am having this error when i train the code on my data , it crashing after the 5th epoch when the validation supposed to happen 

for i in range(crop_num1):
        for j in range(crop_num2):
            # add image to empty_array at specific position
            empty_array[dim1_stride*i:dim1_stride*i + crop_size,
                        dim2_stride*j:dim2_stride*j + crop_size] += image[index]
            index += 1
    return empty_array

**Comment by PyeongKim** [comment]
Sorry for answering late. 
What is the dimension of your data?

**Comment by Ng-ms** [comment]
I  have 20 image , and I resize them to 512x512 and all images are in gray scale

**Comment by PyeongKim** [comment]
Could you show how the error is asserted in your terminal window?

**Comment by Ng-ms** [comment]
IndexError                                Traceback (most recent call last)
<ipython-input-34-d8ccfac27aaf> in <module>()
     43         # Validation every 5 epoch
     44         if (i+1) % 5 == 0:
---> 45             val_acc, val_loss = validate_model(model, SEM_val_load, criterion, i+1, True, image_save_path)
     46             print('Val loss:', val_loss, "val acc:", val_acc)
     47             values = [i+1, train_loss, train_acc, val_loss, val_acc]

2 frames
<ipython-input-2-5f7f152472f3> in image_concatenate(image, crop_num1, crop_num2, dim1, dim2)
    334             # add image to empty_array at specific position
    335             empty_array[dim1_stride*i:dim1_stride*i + crop_size,
--> 336                         dim2_stride*j:dim2_stride*j + crop_size] += image[index]
    337             index += 1
    338     return empty_array

IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by Ng-ms** [comment]
i am running it on google colab

**Comment by Ng-ms** [comment]
and how does  image_concatenate works ? i do not understand this part of the code

**Comment by PyeongKim** [comment]
there should be * between dim2_stride and j like dim2_stride*j. 
Do you have that?

**Comment by Najat91** [comment]
`def image_concatenate(image, crop_num1, crop_num2, dim1, dim2):
    """concatenate images
    Args :
        image : output images (should be square)
        crop_num2 (int) : number of crop in horizontal way (2)
        crop_num1 (int) : number of crop in vertical way (2)
        dim1(int) : vertical size of output (512)
        dim2(int) : horizontal size_of_output (512)
    Return :
        div_array : numpy arrays of numbers of 1,2,4
    """
    crop_size = image.shape[1]  # size of crop
    empty_array = np.zeros([dim1, dim2]).astype("float64")  # to make sure no overflow
    dim1_stride = stride_size(dim1, crop_num1, crop_size)  # vertical stride
    dim2_stride = stride_size(dim2, crop_num2, crop_size)  # horizontal stride
    index = 0
    for i in range(crop_num1):
        for j in range(crop_num2):
            # add image to empty_array at specific position
            empty_array[dim1_stride*i:dim1_stride*i + crop_size,
            dim2_stride*j:dim2_stride*j + crop_size] += image[index]
            imdex+= 1
    return empty_array`

yes i do have it

**Comment by Ng-ms** [comment]
yes i do have it 
empty_array[dim1_stride*i:dim1_stride*i + crop_size,
            dim2_stride*j:dim2_stride*j + crop_size] += image[index]

**Comment by Ng-ms** [comment]
can you please explane to me how the  image_concatenate works

**Comment by PyeongKim** [comment]
The image_concatenate works as following.
1. from validation dataset, we cropped four images in order to fit whole validation image. (Since we cropped 388x388 of image and pad, we have to do same thing in validation).
2. After generating outputs (and corresponding predictions) of four images, these predictions are placed in correct location. For example, the first image represents the first part of the image (0-387 in width, and 0-387 in height). Then the second image represents the second part of the image (124-511 in width and 0-387 in height). In empty_array which is 512x512, we add the prediction in corresponding place. 
3. Since, there is overlapping part in the empty_array after adding up predictions, we divide by number of overlapping (this division is in division_array).

**Comment by Ng-ms** [comment]
the size can be changed to (512 x 512 )  instead of (388X388)?

**Comment by Ng-ms** [comment]
another question, what should i change in the validation model to not image_concatenate 
since the shape of the image and the mask of the validation is 
for images torch.Size([1, 4, 512, 512, 3])
for mask torch.Size([1, 4, 512, 512])
and they are causing the dim error

**Comment by PyeongKim** [comment]
You have three channel in your data. 
In gray scale (at least in our dataset.py) it should not have additional dimension for channel. It should be [1,4,512,512].

**Comment by Ng-ms** [comment]
so what does in_size=572, out_size=388   represent if the size is 512?

**Comment by utkuozbulak** [comment]
Hey, I suggest you read the initial paper and have a look at the dataset file in order to better understand in-out sizes as well as the padding.
