### ISSUE TITLE
Has the weight map for each pixel been used to get better boundaries between cells?

### ISSUE THREAD

**Issue by pratikm141** [ugent-korea/pytorch-unet-segmentation#4]
Hi, in the UNet paper, the authors have said that they had to use pre calculated weights so that the UNet generated more loss at the boundaries between cells while training. Have you used such weights?

**Comment by PyeongKim** [comment]
We did not implemented the pre-calculated weights. It is quite laborious. Instead of that we tried assigning different weights on different classes.
